### PR TITLE
test AsyncGeneratorFunction's basic properties

### PR DESCRIPTION
**Pull request by thefourtheye**
Included basic tests for  properties of `AsyncGeneratorFunction` to begin with.

cc @benjamingr

### CODE REVIEW

**Comment by benjamingr** [comment]
Great start, I'll work on it this Friday!

**Comment by caitp** [comment]
Based on @bterlson's earlier work on tests for async functions, I think built-ins/AsyncGeneratorFunction/ is a good place to put tests on properties of AsyncGeneratorFunction instances.

How about something like this?

```js
// https://tc39.github.io/proposal-async-iteration/#sec-asyncgenerator-definitions-instantiatefunctionobject
var AsyncGeneratorFunction = async function*() { }.constructor;
async function* fn() { };
assert.sameValue(Object.getPrototypeOf(fn.prototype), AsyncGeneratorFunction.prototype.prototype,
	             "fn.prototype should have a [[Prototype]] of %AsyncGeneratorPrototype%");
verifyWritable(fn, "prototype");
verifyNotEnumerable(fn, "prototype");
verifyNotConfigurable(fn, "prototype");
```

Brian's work has some other good examples of useful tests, like verifying the behaviour of CreateDynamicFunction + async generator objects

**Comment by benjamingr** [comment]
Going to copy this to the new PR.

**Comment by benjamingr** [comment]
Copied what I could and rewrote the rest in the new format.

**Pull request closed without merging**
